# Generated by Django 5.0.3 on 2024-04-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время наблюдения')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Температура (°C)')),
                ('humidity', models.IntegerField(verbose_name='Влажность (%)')),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скорость ветра (км/ч)')),
                ('description', models.CharField(max_length=255, verbose_name='Описание погоды')),
            ],
            options={
                'verbose_name': 'Отчет о погоде',
                'verbose_name_plural': 'Отчеты о погоде',
            },
        ),
    ]
